# Generated by Django 2.2.24 on 2023-12-06 13:50

from django.db import migrations

def fill_in_the_fields(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gt=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_in_the_fields)
    ]
