# Generated by Django 2.2.24 on 2023-12-08 23:09

from django.db import migrations
import phonenumbers
def phone_number_conversion(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        pure_phone = phonenumbers.parse(f"{flat.owners_phonenumber}", 'RU')
        flat.owner_pure_phone = phonenumbers.format_number(pure_phone, phonenumbers.PhoneNumberFormat.E164)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20231207_1807'),
    ]

    operations = [
        migrations.RunPython(phone_number_conversion)
    ]
