# Generated by Django 2.2.24 on 2023-12-09 07:18

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20231209_0209'),
    ]

    operations = [
    ]
