# Generated by Django 2.2.24 on 2023-12-09 09:30

from django.db import migrations
import phonenumbers
def phone_number_conversion(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        pure_phone = phonenumbers.parse(f"{flat.owners_phonenumber}", 'RU')
        if phonenumbers.is_valid_number(pure_phone):
            flat.owner_pure_phone = phonenumbers.format_number(pure_phone, phonenumbers.PhoneNumberFormat.E164)
            flat.save()
        else:
            flat.owner_pure_phone = None
            flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20231209_1128'),
    ]

    operations = [
        migrations.RunPython(phone_number_conversion)
    ]
