# Generated by Django 2.2.24 on 2023-12-09 09:30

from django.db import migrations
import phonenumbers
def phone_number_conversion(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flat_objects = Flat.objects.all().iterator()
    for flat in flat_objects:
        phonenumber_to_str = f"{flat.owners_phonenumber}"
        pure_phone = phonenumbers.parse(phonenumber_to_str, 'RU')
        flat.owner_pure_phone = None
        if phonenumbers.is_valid_number(pure_phone):
            flat.owner_pure_phone = phonenumbers.format_number(pure_phone, phonenumbers.PhoneNumberFormat.E164)
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20231209_1128'),
    ]

    operations = [
        migrations.RunPython(phone_number_conversion)
    ]
