# Generated by Django 2.2.24 on 2023-12-10 12:40

from django.db import migrations


def owners_fill(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    owner_objects = Owner.objects.all().iterator()
    for owner in owner_objects:
        owner.flats.set(Flat.objects.filter(owner=owner.name))


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20231210_1540'),
    ]

    operations = [
        migrations.RunPython(owners_fill)
    ]
